<a href="https://colab.research.google.com/github/mukhammadiev01-1/ai_fndtn/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [10]:
print(pd.__version__)

2.2.2

In [12]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "KIA", "Honda", "Ford", "Toyota"],
  'passings': [3, 7, 2, 6, 8, 3, 5, 9]
}

df = pd.DataFrame(mydataset)
print(df)

     cars  passings
0     BMW         3
1   Volvo         7
2    Ford         2
3   Tesla         6
4     KIA         8
5   Honda         3
6    Ford         5
7  Toyota         9

In [15]:
df.head() #default 5 rows

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
3  Tesla         6
4    KIA         8

In [18]:
df.tail() #default 5 rows from last

     cars  passings
3   Tesla         6
4     KIA         8
5   Honda         3
6    Ford         5
7  Toyota         9

In [20]:
df.shape

(8, 2)

In [21]:
df.columns

Index(['cars', 'passings'], dtype='object')

In [22]:
df.dtypes

cars        object
passings     int64
dtype: object

In [25]:
df.describe(include="all") #numerical columns only

        cars  passings
count      8  8.000000
unique     7       NaN
top     Ford       NaN
freq       2       NaN
mean     NaN  5.375000
std      NaN  2.559994
min      NaN  2.000000
25%      NaN  3.000000
50%      NaN  5.500000
75%      NaN  7.250000
max      NaN  9.000000

In [28]:
df.iloc[0:3]

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [32]:
df.loc[2:6, "cars"]

2     Ford
3    Tesla
4      KIA
5    Honda
6     Ford
Name: cars, dtype: object

In [33]:
print(df)

     cars  passings
0     BMW         3
1   Volvo         7
2    Ford         2
3   Tesla         6
4     KIA         8
5   Honda         3
6    Ford         5
7  Toyota         9

In [39]:
df[df["passings"] > 3]

     cars  passings
1   Volvo         7
3   Tesla         6
4     KIA         8
6    Ford         5
7  Toyota         9

In [42]:
#df.mean(numeric_only=True)
df["passings"].mean()

np.float64(5.375)

In [43]:
df.sum()

cars        BMWVolvoFordTeslaKIAHondaFordToyota
passings                                     43
dtype: object

In [44]:
df.min()

cars        BMW
passings      2
dtype: object

In [45]:
df.max()

cars        Volvo
passings        9
dtype: object

In [46]:
df.median(numeric_only=True)

passings    5.5
dtype: float64

In [47]:
df.count()

cars        8
passings    8
dtype: int64

In [48]:
df.std(numeric_only=True)

passings    2.559994
dtype: float64

In [50]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [52]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [53]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [54]:
df_missing.fillna(0)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2        0     0.0
3    Tesla     8.0
4  Ferrari     1.0
5        0     9.0
6     Ford     0.0

In [56]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(100)

#

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(100)

#df = pd.read_excel("Titanic-Dataset.xlsx")
#df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [57]:
df.to_excel("test.xlsx")

In [58]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [59]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']